/**
 * AI Tutor integration. Pure module.
 *
 * COMPONENT BOUNDARY. This component observes, estimates state and requests
 * support. It does NOT write explanations, choose worked examples or author
 * scaffold steps: that is the Adaptive Learning / AI Tutor component. Everything
 * here is the request side of that contract.
 *
 * The payload is intentionally about the LEARNER SITUATION, not about a UI. The
 * tutor decides what to render; we only say what kind of help is warranted and
 * on what evidence.
 */

import { SUPPORT_NEED, SUPPORT_TYPE } from '../../data/learner-state/supportCopy';

/** Support types that need the tutor to generate content. */
export const TUTOR_SUPPORT_TYPES = new Set([SUPPORT_TYPE.HINT, SUPPORT_TYPE.SCAFFOLD]);

/**
 * Builds the support request handed to the AI Tutor.
 *
 * @param {object} input
 * @param {string} input.learnerId
 * @param {string} input.sessionId
 * @param {object} input.window   - the TemporalWindow that produced the decision
 * @param {object} input.decision - output of `decideSupport`
 * @param {object} input.weakAreaContext - from Learner Profile / Assessment
 * @param {Array}  input.recentAttempts  - from the Gamified Learning Module
 */
export function buildTutorSupportRequest({
  learnerId,
  sessionId,
  window,
  decision,
  weakAreaContext = null,
  recentAttempts = [],
} = {}) {
  if (!decision) return null;

  return {
    learnerId,
    sessionId,
    learnerState: decision.disengagement > decision.confusion ? 'disengagement' : 'confusion',
    supportNeed: decision.supportNeed,
    supportType: decision.supportType,
    confidence: decision.confidence,
    persistenceTrend: decision.trend,
    weakAreaContext,
    recentAttempts,

    // Evidence block. Included so the tutor can calibrate how much to say, and so
    // a reviewer can see the request was not made on a single frame.
    evidence: {
      windowId: window?.id ?? null,
      windowSeconds: window?.durationSec ?? null,
      confusionProbability: decision.confusion,
      disengagementProbability: decision.disengagement,
      persistenceScore: decision.persistenceScore,
      consecutiveConfusionWindows: decision.confusionRun,
      visualReliability: window?.stateEstimate?.visualReliability ?? 0,
      behaviorReliability: window?.stateEstimate?.behaviorReliability ?? 0,
      visualWeight: window?.stateEstimate?.visualWeight ?? 0,
      behaviorWeight: window?.stateEstimate?.behaviorWeight ?? 1,
      baselineSummary: window?.baselineDeviation?.summary ?? null,
      cameraMode: window?.cameraMode ?? null,
    },

    requestedAt: window?.endTime ?? null,
    // Names the boundary explicitly in the payload the other team reads.
    origin: 'learner-state-detection',
    note: 'Support request only. Explanation and scaffold content are generated by the AI Tutor.',
  };
}

/**
 * Delivery seam. Swap this for the real tutor endpoint or an in-app dispatch
 * without touching any decision logic.
 */
export async function sendSupportRequest(payload, { transport } = {}) {
  if (!payload) return { delivered: false, reason: 'No payload' };

  if (typeof transport === 'function') {
    const response = await transport(payload);
    return { delivered: true, response };
  }

  // Prototype default: the request is recorded and surfaced in the research
  // panel rather than posted anywhere.
  return { delivered: true, response: { accepted: true, simulated: true } };
}

/** Whether this decision should reach the tutor at all. */
export function requiresTutor(decision) {
  return (
    decision?.supportNeed === SUPPORT_NEED.INTERVENE &&
    TUTOR_SUPPORT_TYPES.has(decision.supportType)
  );
}

/**
 * Non-tutor interventions are requests to the Gamified Learning Module instead:
 * change the activity, offer a break, run a short challenge.
 */
export function buildActivityRequest({ sessionId, decision } = {}) {
  if (!decision || decision.supportNeed !== SUPPORT_NEED.INTERVENE) return null;
  if (TUTOR_SUPPORT_TYPES.has(decision.supportType)) return null;

  return {
    sessionId,
    target: 'gamified-learning',
    action: decision.supportType,
    persistenceTrend: decision.trend,
    confidence: decision.confidence,
  };
}
